In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option('display.max_columns', None)
plt.style.use('seaborn-v0_8-whitegrid')

LOAD DATASET

In [ ]:
df =  pd.read_csv("/content/drive/MyDrive/DatasetMeasles/DatasetMeasles.csv", encoding='latin1')

In [ ]:
df

,Country,Year,Population,Reported_measles_cases,Suspected_measles_cases,Measles_deaths,MCV1_coverage (%),MCV2_coverage (%),DTP3_coverage (%),Population_density (people/km²),Urbanization (%),"Birth_rate (per 1,000)",Proportion_under5 (%),GDP_per_capita (US$),Health_expenditure_per_capita (US$),Hospital_beds_per_1000,Physicians_per_10000,Vaccine_stock_status,Outbreak_alert,GoogleTrends_index,Dropout_rate (MCV1?MCV2),Measles_incidence_rate (per million),SIAs_in_past_3yrs,Air_travel_volume (million passengers),Internet_penetration (%),Routine_immunization_dropout (%),Outbreak_Label,Avg_Annual_Temperature,Total_Annual_Rainfall,Avg_Annual_Humidity,Rainy_Season_Length,Temp_Seasonality,Dry_Season_Length,Extreme_Rain_Days
0,Nigeria,1990,"97,120,925","38,500","43,000","1,850",54,NaN,40,106.6,36.2,47.8,20.6,450,15.36,0.5,2.00,Insufficient,TRUE,NaN,NaN,NaN,NaN,1.3,0.01,NaN,TRUE,26.8,1150,68,7,2.4,5,32
1,Nigeria,2000,"126,382,494","30,000","36,000","1,200",51,NaN,48,137,36.7,43.5,19.4,390,24.92,0.5,2.20,Insufficient,Yes,NaN,NaN,NaN,NaN,2.9,0.06,NaN,TRUE,27.1,1205,70,7,2.3,5,35
2,Nigeria,2010,"158,733,000","21,000","26,000",800,63.6,25,70,180,41.4,39.5,18.2,"1,400",49.9,0.5,3.95,Adequate,Yes,NaN,NaN,NaN,Yes,7.1,24,NaN,TRUE,27.4,1240,72,7,2.2,5,38
3,Nigeria,2021,"218,529,286","12,973","14,500",310,69,54,71,236,52.7,33.5,16.5,"2,400",81.87,0.9,3.95,Adequate,Yes,NaN,24,45.8,Yes,14,50,24.0,TRUE,27.9,1305,74,8,2.1,4,42
4,Indonesia,1990,"181,413,402","9,000","12,000",450,64,NaN,60,96.8,30.6,27.7,14.9,560,17.94,0.6,1.50,Insufficient,Yes,NaN,NaN,NaN,NaN,6,0.04,NaN,TRUE,26.3,2700,80,9,1.2,3,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Peru,2022,"34,000,000",150,190,1,95,89,96,26,79.0,21,11.8,"7,500",720,1.6,16.00,Adequate,No,33.0,6,5,Yes,17.5,52,3.0,Non-outbreak,~20.8,~970,~76,~4,~10,~8,~16
156,Ukraine,1994,"51,500,000","15,000","17,000",300,81,58,84,85,66.0,11.9,6.5,"2,800",250,10,39.00,Adequate,Yes,66.0,23,291,Yes,4.1,12,9.0,Outbreak,~7.5,~500,~70,~3,~15,~8,~10
157,Ukraine,2003,"47,800,000",300,400,2,89,80,91,81,68.0,10.4,5.9,"4,200",380,8.8,40.00,Adequate,No,42.0,9,6,Yes,5.2,15,4.0,Non-outbreak,~8.0,~520,~70,~3,~15,~8,~11
158,Ukraine,2017,"44,500,000","23,000","25,000",120,85,65,87,77,70.0,9.7,5.5,"8,300",800,8,42.00,Adequate,Yes,72.0,20,517,Yes,10.3,40,8.0,Outbreak,~8.5,~540,~71,~3,~15,~8,~11
159,Ukraine,2022,"41,000,000","1,200","1,500",6,93,88,95,74,71.0,9.3,5.2,"12,400","1,100",7.8,43.00,Adequate,No,35.0,5,29,Yes,19.2,82,3.0,Non-outbreak,~8.8,~550,~71,~3,~15,~8,~12

In [ ]:
df.head()

,Country,Year,Population,Reported_measles_cases,Suspected_measles_cases,Measles_deaths,MCV1_coverage (%),MCV2_coverage (%),DTP3_coverage (%),Population_density (people/km²),Urbanization (%),"Birth_rate (per 1,000)",Proportion_under5 (%),GDP_per_capita (US$),Health_expenditure_per_capita (US$),Hospital_beds_per_1000,Physicians_per_10000,Vaccine_stock_status,Outbreak_alert,GoogleTrends_index,Dropout_rate (MCV1?MCV2),Measles_incidence_rate (per million),SIAs_in_past_3yrs,Air_travel_volume (million passengers),Internet_penetration (%),Routine_immunization_dropout (%),Outbreak_Label,Avg_Annual_Temperature,Total_Annual_Rainfall,Avg_Annual_Humidity,Rainy_Season_Length,Temp_Seasonality,Dry_Season_Length,Extreme_Rain_Days
0,Nigeria,1990,"97,120,925","38,500","43,000","1,850",54,NaN,40,106.6,36.2,47.8,20.6,450,15.36,0.5,2.00,Insufficient,TRUE,NaN,NaN,NaN,NaN,1.3,0.01,NaN,TRUE,26.8,1150,68,7,2.4,5,32
1,Nigeria,2000,"126,382,494","30,000","36,000","1,200",51,NaN,48,137,36.7,43.5,19.4,390,24.92,0.5,2.20,Insufficient,Yes,NaN,NaN,NaN,NaN,2.9,0.06,NaN,TRUE,27.1,1205,70,7,2.3,5,35
2,Nigeria,2010,"158,733,000","21,000","26,000",800,63.6,25,70,180,41.4,39.5,18.2,"1,400",49.9,0.5,3.95,Adequate,Yes,NaN,NaN,NaN,Yes,7.1,24,NaN,TRUE,27.4,1240,72,7,2.2,5,38
3,Nigeria,2021,"218,529,286","12,973","14,500",310,69,54,71,236,52.7,33.5,16.5,"2,400",81.87,0.9,3.95,Adequate,Yes,NaN,24,45.8,Yes,14,50,24.0,TRUE,27.9,1305,74,8,2.1,4,42
4,Indonesia,1990,"181,413,402","9,000","12,000",450,64,NaN,60,96.8,30.6,27.7,14.9,560,17.94,0.6,1.50,Insufficient,Yes,NaN,NaN,NaN,NaN,6,0.04,NaN,TRUE,26.3,2700,80,9,1.2,3,75

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 160 non-null    object
 1   Year                                    160 non-null    int64
 2   Population                              160 non-null    object
 3   Reported_measles_cases                  151 non-null    object
 4   Suspected_measles_cases                 48 non-null     object
 5   Measles_deaths                          150 non-null    object
 6   MCV1_coverage (%)                       159 non-null    object
 7   MCV2_coverage (%)                       120 non-null    object
 8   DTP3_coverage (%)                       155 non-null    object
 9   Population_density (people/km²)         160 non-null    object
 10  Urbanization (%)                        160 non-null    float64
 11  Birth_rate (per 1,000)                  160 non-null    object
 12  Proportion_under5 (%)                   159 non-null    object
 13  GDP_per_capita (US$)                    157 non-null    object
 14  Health_expenditure_per_capita (US$)     138 non-null    object
 15  Hospital_beds_per_1000                  158 non-null    object
 16  Physicians_per_10000                    159 non-null    float64
 17  Vaccine_stock_status                    92 non-null     object
 18  Outbreak_alert                          160 non-null    object
 19  GoogleTrends_index                      40 non-null     float64
 20  Dropout_rate (MCV1?MCV2)                108 non-null    object
 21  Measles_incidence_rate (per million)    144 non-null    object
 22  SIAs_in_past_3yrs                       156 non-null    object
 23  Air_travel_volume (million passengers)  160 non-null    object
 24  Internet_penetration (%)                160 non-null    object
 25  Routine_immunization_dropout (%)        85 non-null     float64
 26  Outbreak_Label                          159 non-null    object
 27  Avg_Annual_Temperature                  160 non-null    object
 28  Total_Annual_Rainfall                   160 non-null    object
 29  Avg_Annual_Humidity                     160 non-null    object
 30  Rainy_Season_Length                     160 non-null    object
 31  Temp_Seasonality                        160 non-null    object
 32  Dry_Season_Length                       160 non-null    object
 33  Extreme_Rain_Days                       160 non-null    object
dtypes: float64(4), int64(1), object(29)
memory usage: 42.6+ KB

In [ ]:
df.dtypes

Country                                    object
Year                                        int64
Population                                 object
Reported_measles_cases                     object
Suspected_measles_cases                    object
Measles_deaths                             object
MCV1_coverage (%)                          object
MCV2_coverage (%)                          object
DTP3_coverage (%)                          object
Population_density (people/km²)            object
Urbanization (%)                          float64
Birth_rate (per 1,000)                     object
Proportion_under5 (%)                      object
GDP_per_capita (US$)                       object
Health_expenditure_per_capita (US$)        object
Hospital_beds_per_1000                     object
Physicians_per_10000                      float64
Vaccine_stock_status                       object
Outbreak_alert                             object
GoogleTrends_index                        float64
Dropout_rate (MCV1?MCV2)                   object
Measles_incidence_rate (per million)       object
SIAs_in_past_3yrs                          object
Air_travel_volume (million passengers)     object
Internet_penetration (%)                   object
Routine_immunization_dropout (%)          float64
Outbreak_Label                             object
Avg_Annual_Temperature                     object
Total_Annual_Rainfall                      object
Avg_Annual_Humidity                        object
Rainy_Season_Length                        object
Temp_Seasonality                           object
Dry_Season_Length                          object
Extreme_Rain_Days                          object
dtype: object

Treating Null Values

In [ ]:
df.isnull().sum()

Country                                     0
Year                                        0
Population                                  0
Reported_measles_cases                      9
Suspected_measles_cases                   112
Measles_deaths                             10
MCV1_coverage (%)                           1
MCV2_coverage (%)                          40
DTP3_coverage (%)                           5
Population_density (people/km²)             0
Urbanization (%)                            0
Birth_rate (per 1,000)                      0
Proportion_under5 (%)                       1
GDP_per_capita (US$)                        3
Health_expenditure_per_capita (US$)        22
Hospital_beds_per_1000                      2
Physicians_per_10000                        1
Vaccine_stock_status                       68
Outbreak_alert                              0
GoogleTrends_index                        120
Dropout_rate (MCV1?MCV2)                   52
Measles_incidence_rate (per million)       16
SIAs_in_past_3yrs                           4
Air_travel_volume (million passengers)      0
Internet_penetration (%)                    0
Routine_immunization_dropout (%)           75
Outbreak_Label                              1
Avg_Annual_Temperature                      0
Total_Annual_Rainfall                       0
Avg_Annual_Humidity                         0
Rainy_Season_Length                         0
Temp_Seasonality                            0
Dry_Season_Length                           0
Extreme_Rain_Days                           0
dtype: int64

In [ ]:
# Sort properly
df = df.sort_values(['Country', 'Year'])

# Forward/backward fill within country
df = df.groupby('Country').apply(lambda x: x.ffill().bfill())

# Fill any remaining numeric nulls with median
df = df.fillna(df.median(numeric_only=True))

# Fill categorical separately
df['Vaccine_stock_status'] = df['Vaccine_stock_status'].fillna('Unknown')

/tmp/ipython-input-3889420830.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.groupby('Country').apply(lambda x: x.ffill().bfill())
/tmp/ipython-input-3889420830.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('Country').apply(lambda x: x.ffill().bfill())

In [ ]:
df

                 Country  Year  Population Reported_measles_cases  \
Country
Argentina 108  Argentina  1990  32,000,000                  8,000
          109  Argentina  2006  39,200,000                    500
          110  Argentina  2018  44,400,000                  3,000
          111  Argentina  2020  45,200,000                    400
Australia 128  Australia  1990  17,200,000                  2,300
...                  ...   ...         ...                    ...
Vietnam   103    Vietnam  2020  97,300,000                    400
Yemen     132      Yemen  1995  15,000,000                  9,800
          133      Yemen  2005  20,500,000                  5,500
          134      Yemen  2015  27,000,000                 13,200
          135      Yemen  2022  31,000,000                  3,400

              Suspected_measles_cases Measles_deaths MCV1_coverage (%)  \
Country
Argentina 108                     NaN            150                75
          109                     NaN             10                95
          110                     NaN             40                90
          111                     NaN              5                95
Australia 128                   2,800              5                87
...                               ...            ...               ...
Vietnam   103                     NaN              5                97
Yemen     132                  11,200            420                52
          133                   6,000            230                63
          134                  15,000            590                72
          135                   4,100            190                75

              MCV2_coverage (%) DTP3_coverage (%)  \
Country
Argentina 108                90                80
          109                90                95
          110                86                92
          111                92                95
Australia 128                70                90
...                         ...               ...
Vietnam   103                90                96
Yemen     132                18                56
          133                35                70
          134                45                76
          135                52                79

              Population_density (people/km²)  Urbanization (%)  \
Country
Argentina 108                              15              87.0
          109                              16              89.0
          110                              16              90.0
          111                              17              90.0
Australia 128                             2.3              84.0
...                                       ...               ...
Vietnam   103                             300              38.0
Yemen     132                              27              23.0
          133                              32              26.0
          134                              38              28.0
          135                              40              31.0

              Birth_rate (per 1,000) Proportion_under5 (%)  \
Country
Argentina 108                     22                     9
          109                     18                     8
          110                     16                     7
          111                     15                   6.5
Australia 128                   15.5                   8.5
...                              ...                   ...
Vietnam   103                     15                    12
Yemen     132                   41.5                  23.1
          133                   37.1                  20.5
          134                   34.8                  18.2
          135                     31                  16.8

              GDP_per_capita (US$) Health_expenditure_per_capita (US$)  \
Country
Argentina 108                4,800                                 220
          109                7,500                                 550
          110               10,000                                 800
          111                9,900                                 850
Australia 128               18,000                               1,900
...                            ...                                 ...
Vietnam   103                3,600                                 400
Yemen     132                  480                                  38
          133                  710                                  55
          134                  900                                  65
          135                1,050                                  72

              Hospital_beds_per_1000  Physicians_per_10000  \
Country
Argentina 108                      3                  18.0
          109                    3.2                  20.0
          110                    3.5                  23.0
          111                    3.5                  24.0
Australia 128                      7                  30.0
...                              ...                   ...
Vietnam   103                    2.3                  10.0
Yemen     132                    0.4                   2.0
          133                    0.5                   3.0
          134                    0.3                   2.0
          135                    0.4                   2.0

              Vaccine_stock_status Outbreak_alert  GoogleTrends_index  \
Country
Argentina 108              Limited           TRUE                50.0
          109             Adequate           TRUE                50.0
          110              Limited          FALSE                50.0
          111               Stable           TRUE                50.0
Australia 128             Adequate            Yes                46.0
...                            ...            ...                 ...
Vietnam   103               Stable           TRUE                50.0
Yemen     132              Limited            Yes                61.0
          133              Limited             No                48.0
          134              Limited            Yes                67.0
          135              Limited             No                43.0

              Dropout_rate (MCV1?MCV2) Measles_incidence_rate (per million)  \
Country
Argentina 108                        2                                  250
          109                        2                                 12.8
          110                        4                                 67.6
          111                        3                                  8.9
Australia 128                       17                                  134
...                                ...                                  ...
Vietnam   103                        7                                  4.1
Yemen     132                       34                                  653
          133                       28                                  268
          134                       27                                  489
          135                       23                                  110

              SIAs_in_past_3yrs Air_travel_volume (million passengers)  \
Country
Argentina 108                No                                      5
          109               Yes                                     14
          110               Yes                                     25
          111               Yes                                     30
Australia 128               Yes                                     15
...                         ...                                    ...
Vietnam   103               Yes                                      7
Yemen     132               Yes                                    0.6
          133               Yes                                    1.4
          134               Yes                                    2.1
          135               Yes                                    2.8

              Internet_penetration (%)  Routine_immunization_dropout (%)  \
Country
Argentina 108                        3                              15.0
          109                       45                               4.0
          110                       82                               8.0
          111                       85                               2.0
Australia 128                       25                               6.0
...                                ...                               ...
Vietnam   103                       70                               3.0
Yemen     132                        1                              18.0
          133                        2                              14.0
          134                        3                              16.0
          135                        5                              12.0

              Outbreak_Label Avg_Annual_Temperature Total_Annual_Rainfall  \
Country
Argentina 108           TRUE                  ~18.0                  ~900
          109           TRUE                  ~18.3                  ~910
          110          FALSE                  ~18.6                  ~920
          111           TRUE                  ~18.8                  ~925
Australia 128       Outbreak                  ~21.0                  ~500
...                      ...                    ...                   ...
Vietnam   103           TRUE                  ~26.0                 ~1560
Yemen     132       Outbreak                  ~27.0                  ~200
          133   Non-outbreak                  ~27.2                  ~210
          134       Outbreak                  ~27.5                  ~215
          135   Non-outbreak                  ~27.8                  ~220

              Avg_Annual_Humidity Rainy_Season_Length Temp_Seasonality  \
Country
Argentina 108                 ~65                  ~4              ~10
          109                 ~65                  ~4              ~10
          110                 ~66                  ~4              ~11
          111                 ~66                  ~4              ~11
Australia 128                 ~60                  ~2              ~10
...                           ...                 ...              ...
Vietnam   103                 ~76                  ~5               ~7
Yemen     132                 ~50                  ~2              ~12
          133                 ~50                  ~2              ~12
          134                 ~51                  ~2              ~12
          135                 ~51                  ~2              ~12

              Dry_Season_Length Extreme_Rain_Days
Country
Argentina 108                ~8               ~18
          109                ~8               ~18
          110                ~8               ~19
          111                ~8               ~19
Australia 128               ~10                ~8
...                         ...               ...
Vietnam   103                ~7               ~27
Yemen     132               ~10                ~6
          133               ~10                ~6
          134               ~10                ~7
          135               ~10                ~7

[160 rows x 34 columns]

In [ ]:
df.isnull().sum()

Country                                     0
Year                                        0
Population                                  0
Reported_measles_cases                      0
Suspected_measles_cases                   112
Measles_deaths                              0
MCV1_coverage (%)                           0
MCV2_coverage (%)                           4
DTP3_coverage (%)                           0
Population_density (people/km²)             0
Urbanization (%)                            0
Birth_rate (per 1,000)                      0
Proportion_under5 (%)                       0
GDP_per_capita (US$)                        0
Health_expenditure_per_capita (US$)         8
Hospital_beds_per_1000                      0
Physicians_per_10000                        0
Vaccine_stock_status                        0
Outbreak_alert                              0
GoogleTrends_index                          0
Dropout_rate (MCV1?MCV2)                    8
Measles_incidence_rate (per million)        4
SIAs_in_past_3yrs                           0
Air_travel_volume (million passengers)      0
Internet_penetration (%)                    0
Routine_immunization_dropout (%)            0
Outbreak_Label                              0
Avg_Annual_Temperature                      0
Total_Annual_Rainfall                       0
Avg_Annual_Humidity                         0
Rainy_Season_Length                         0
Temp_Seasonality                            0
Dry_Season_Length                           0
Extreme_Rain_Days                           0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 160 entries, ('Argentina', np.int64(108)) to ('Yemen', np.int64(135))
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 160 non-null    object
 1   Year                                    160 non-null    int64
 2   Population                              160 non-null    object
 3   Reported_measles_cases                  160 non-null    object
 4   Suspected_measles_cases                 48 non-null     object
 5   Measles_deaths                          160 non-null    object
 6   MCV1_coverage (%)                       160 non-null    object
 7   MCV2_coverage (%)                       156 non-null    object
 8   DTP3_coverage (%)                       160 non-null    object
 9   Population_density (people/km²)         160 non-null    object
 10  Urbanization (%)                        160 non-null    float64
 11  Birth_rate (per 1,000)                  160 non-null    object
 12  Proportion_under5 (%)                   160 non-null    object
 13  GDP_per_capita (US$)                    160 non-null    object
 14  Health_expenditure_per_capita (US$)     152 non-null    object
 15  Hospital_beds_per_1000                  160 non-null    object
 16  Physicians_per_10000                    160 non-null    float64
 17  Vaccine_stock_status                    160 non-null    object
 18  Outbreak_alert                          160 non-null    object
 19  GoogleTrends_index                      160 non-null    float64
 20  Dropout_rate (MCV1?MCV2)                152 non-null    object
 21  Measles_incidence_rate (per million)    156 non-null    object
 22  SIAs_in_past_3yrs                       160 non-null    object
 23  Air_travel_volume (million passengers)  160 non-null    object
 24  Internet_penetration (%)                160 non-null    object
 25  Routine_immunization_dropout (%)        160 non-null    float64
 26  Outbreak_Label                          160 non-null    object
 27  Avg_Annual_Temperature                  160 non-null    object
 28  Total_Annual_Rainfall                   160 non-null    object
 29  Avg_Annual_Humidity                     160 non-null    object
 30  Rainy_Season_Length                     160 non-null    object
 31  Temp_Seasonality                        160 non-null    object
 32  Dry_Season_Length                       160 non-null    object
 33  Extreme_Rain_Days                       160 non-null    object
dtypes: float64(4), int64(1), object(29)
memory usage: 49.7+ KB

In [ ]:
numeric_cols = [
    'Suspected_measles_cases',
    'MCV2_coverage (%)',
    'Health_expenditure_per_capita (US$)',
    'Dropout_rate (MCV1?MCV2)',
    'Measles_incidence_rate (per million)'
]

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
# Remove commas and convert to numeric
for col in numeric_cols:
    df[col] = (
        df[col]
        .astype(str)                # ensure string
        .str.replace(',', '', regex=False)  # remove commas
        .replace('nan', np.nan)     # fix string 'nan'
    )

    df[col] = pd.to_numeric(df[col], errors='coerce')

In [ ]:

def clean_numeric(col):
    return (
        col.astype(str)
           .str.replace(',', '', regex=False)
           .str.replace('%', '', regex=False)
           .str.replace('$', '', regex=False)
           .str.strip()
           .replace(['', 'nan', 'None'], np.nan)
    )

# Apply to suspected numeric columns
for col in numeric_cols:
    df[col] = pd.to_numeric(clean_numeric(df[col]), errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 160 non-null    object
 1   Year                                    160 non-null    int64
 2   Population                              160 non-null    object
 3   Reported_measles_cases                  160 non-null    object
 4   Suspected_measles_cases                 48 non-null     float64
 5   Measles_deaths                          160 non-null    object
 6   MCV1_coverage (%)                       160 non-null    object
 7   MCV2_coverage (%)                       100 non-null    float64
 8   DTP3_coverage (%)                       160 non-null    object
 9   Population_density (people/km²)         160 non-null    object
 10  Urbanization (%)                        160 non-null    float64
 11  Birth_rate (per 1,000)                  160 non-null    object
 12  Proportion_under5 (%)                   160 non-null    object
 13  GDP_per_capita (US$)                    160 non-null    object
 14  Health_expenditure_per_capita (US$)     101 non-null    float64
 15  Hospital_beds_per_1000                  160 non-null    object
 16  Physicians_per_10000                    160 non-null    float64
 17  Vaccine_stock_status                    160 non-null    object
 18  Outbreak_alert                          160 non-null    object
 19  GoogleTrends_index                      160 non-null    float64
 20  Dropout_rate (MCV1?MCV2)                102 non-null    float64
 21  Measles_incidence_rate (per million)    155 non-null    float64
 22  SIAs_in_past_3yrs                       160 non-null    object
 23  Air_travel_volume (million passengers)  160 non-null    object
 24  Internet_penetration (%)                160 non-null    object
 25  Routine_immunization_dropout (%)        160 non-null    float64
 26  Outbreak_Label                          160 non-null    object
 27  Avg_Annual_Temperature                  160 non-null    object
 28  Total_Annual_Rainfall                   160 non-null    object
 29  Avg_Annual_Humidity                     160 non-null    object
 30  Rainy_Season_Length                     160 non-null    object
 31  Temp_Seasonality                        160 non-null    object
 32  Dry_Season_Length                       160 non-null    object
 33  Extreme_Rain_Days                       160 non-null    object
dtypes: float64(9), int64(1), object(24)
memory usage: 42.6+ KB

In [ ]:
df['Population'] = df['Population'].str.replace(',', '', regex=False)
df['Population'] = pd.to_numeric(df['Population'], errors='coerce')

In [ ]:
# df['Reported_measles_cases'].unique()
df['Reported_measles_cases'] = df['Reported_measles_cases'].str.replace(',', '', regex=False)
df['Reported_measles_cases'] = pd.to_numeric(df['Reported_measles_cases'], errors='coerce')

In [ ]:
# df['Measles_deaths'].unique()
df['Measles_deaths'] = df['Measles_deaths'].str.replace(',', '', regex=False)
df['Measles_deaths'] = pd.to_numeric(df['Measles_deaths'], errors='coerce')

In [ ]:
df['MCV1_coverage (%)'].unique()
df['MCV1_coverage (%)'] = df['MCV1_coverage (%)'].str.replace(',', '', regex=False)
df['MCV1_coverage (%)'] = pd.to_numeric(df['MCV1_coverage (%)'], errors='coerce')

In [ ]:
df['DTP3_coverage (%)'].unique()
df['DTP3_coverage (%)'] = df['DTP3_coverage (%)'].str.replace(',', '', regex=False)
df['DTP3_coverage (%)'] = pd.to_numeric(df['DTP3_coverage (%)'], errors='coerce')

In [ ]:
# df['Population_density (people/km²)'].unique()
df['Population_density (people/km²)'] = df['Population_density (people/km²)'].str.replace(',', '', regex=False)
df['Population_density (people/km²)'] = pd.to_numeric(df['Population_density (people/km²)'], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 160 non-null    object
 1   Year                                    160 non-null    int64
 2   Population                              160 non-null    int64
 3   Reported_measles_cases                  152 non-null    float64
 4   Suspected_measles_cases                 48 non-null     float64
 5   Measles_deaths                          95 non-null     float64
 6   MCV1_coverage (%)                       104 non-null    float64
 7   MCV2_coverage (%)                       100 non-null    float64
 8   DTP3_coverage (%)                       104 non-null    float64
 9   Population_density (people/km²)         160 non-null    float64
 10  Urbanization (%)                        160 non-null    float64
 11  Birth_rate (per 1,000)                  160 non-null    object
 12  Proportion_under5 (%)                   160 non-null    object
 13  GDP_per_capita (US$)                    160 non-null    object
 14  Health_expenditure_per_capita (US$)     101 non-null    float64
 15  Hospital_beds_per_1000                  160 non-null    object
 16  Physicians_per_10000                    160 non-null    float64
 17  Vaccine_stock_status                    160 non-null    object
 18  Outbreak_alert                          160 non-null    object
 19  GoogleTrends_index                      160 non-null    float64
 20  Dropout_rate (MCV1?MCV2)                102 non-null    float64
 21  Measles_incidence_rate (per million)    155 non-null    float64
 22  SIAs_in_past_3yrs                       160 non-null    object
 23  Air_travel_volume (million passengers)  160 non-null    object
 24  Internet_penetration (%)                160 non-null    object
 25  Routine_immunization_dropout (%)        160 non-null    float64
 26  Outbreak_Label                          160 non-null    object
 27  Avg_Annual_Temperature                  160 non-null    object
 28  Total_Annual_Rainfall                   160 non-null    object
 29  Avg_Annual_Humidity                     160 non-null    object
 30  Rainy_Season_Length                     160 non-null    object
 31  Temp_Seasonality                        160 non-null    object
 32  Dry_Season_Length                       160 non-null    object
 33  Extreme_Rain_Days                       160 non-null    object
dtypes: float64(14), int64(2), object(18)
memory usage: 42.6+ KB

In [ ]:
features_to = ['Birth_rate (per 1,000)','Proportion_under5 (%)','GDP_per_capita (US$)','Hospital_beds_per_1000','Vaccine_stock_status','Air_travel_volume (million passengers)','Internet_penetration (%)','Routine_immunization_dropout (%)','Avg_Annual_Temperature','Total_Annual_Rainfall','Avg_Annual_Humidity','Rainy_Season_Length','Temp_Seasonality','Dry_Season_Length','Extreme_Rain_Days']

In [ ]:
for col in features_to:
    # Skip if the column is categorical
    if df[col].dtype == 'object':
        df[col] = df[col].astype(str).str.replace(',', '', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 160 non-null    object
 1   Year                                    160 non-null    int64
 2   Population                              160 non-null    int64
 3   Reported_measles_cases                  152 non-null    float64
 4   Suspected_measles_cases                 48 non-null     float64
 5   Measles_deaths                          95 non-null     float64
 6   MCV1_coverage (%)                       104 non-null    float64
 7   MCV2_coverage (%)                       100 non-null    float64
 8   DTP3_coverage (%)                       104 non-null    float64
 9   Population_density (people/km²)         160 non-null    float64
 10  Urbanization (%)                        160 non-null    float64
 11  Birth_rate (per 1,000)                  159 non-null    float64
 12  Proportion_under5 (%)                   104 non-null    float64
 13  GDP_per_capita (US$)                    160 non-null    int64
 14  Health_expenditure_per_capita (US$)     101 non-null    float64
 15  Hospital_beds_per_1000                  159 non-null    float64
 16  Physicians_per_10000                    160 non-null    float64
 17  Vaccine_stock_status                    0 non-null      float64
 18  Outbreak_alert                          160 non-null    object
 19  GoogleTrends_index                      160 non-null    float64
 20  Dropout_rate (MCV1?MCV2)                102 non-null    float64
 21  Measles_incidence_rate (per million)    155 non-null    float64
 22  SIAs_in_past_3yrs                       160 non-null    object
 23  Air_travel_volume (million passengers)  154 non-null    float64
 24  Internet_penetration (%)                147 non-null    float64
 25  Routine_immunization_dropout (%)        160 non-null    float64
 26  Outbreak_Label                          160 non-null    object
 27  Avg_Annual_Temperature                  100 non-null    float64
 28  Total_Annual_Rainfall                   100 non-null    float64
 29  Avg_Annual_Humidity                     100 non-null    float64
 30  Rainy_Season_Length                     100 non-null    float64
 31  Temp_Seasonality                        100 non-null    float64
 32  Dry_Season_Length                       100 non-null    float64
 33  Extreme_Rain_Days                       100 non-null    float64
dtypes: float64(27), int64(3), object(4)
memory usage: 42.6+ KB

In [ ]:
df.isnull().sum()

Country                                     0
Year                                        0
Population                                  0
Reported_measles_cases                      8
Suspected_measles_cases                   112
Measles_deaths                             65
MCV1_coverage (%)                          56
MCV2_coverage (%)                          60
DTP3_coverage (%)                          56
Population_density (people/km²)             0
Urbanization (%)                            0
Birth_rate (per 1,000)                      1
Proportion_under5 (%)                      56
GDP_per_capita (US$)                        0
Health_expenditure_per_capita (US$)        59
Hospital_beds_per_1000                      1
Physicians_per_10000                        0
Vaccine_stock_status                      160
Outbreak_alert                              0
GoogleTrends_index                          0
Dropout_rate (MCV1?MCV2)                   58
Measles_incidence_rate (per million)        5
SIAs_in_past_3yrs                           0
Air_travel_volume (million passengers)      6
Internet_penetration (%)                   13
Routine_immunization_dropout (%)            0
Outbreak_Label                              0
Avg_Annual_Temperature                     60
Total_Annual_Rainfall                      60
Avg_Annual_Humidity                        60
Rainy_Season_Length                        60
Temp_Seasonality                           60
Dry_Season_Length                          60
Extreme_Rain_Days                          60
dtype: int64

In [ ]:

categorical_cols = ['Country', 'Vaccine_stock_status', 'Outbreak_alert', 'Outbreak_Label']
numeric_cols = [
    'Population', 'Population_density (people/km²)',
    'Reported_measles_cases','Suspected_measles_cases','Measles_deaths',
    'MCV1_coverage (%)','MCV2_coverage (%)','DTP3_coverage (%)',
    'Birth_rate (per 1,000)','Proportion_under5 (%)',
    'GDP_per_capita (US$)','Health_expenditure_per_capita (US$)',
    'Hospital_beds_per_1000','Physicians_per_10000',
    'Air_travel_volume (million passengers)','Internet_penetration (%)',
    'Routine_immunization_dropout (%)','Dropout_rate (MCV1?MCV2)',
    'Measles_incidence_rate (per million)',
    'Avg_Annual_Temperature','Total_Annual_Rainfall','Avg_Annual_Humidity',
    'Rainy_Season_Length','Temp_Seasonality','Dry_Season_Length','Extreme_Rain_Days'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = df[col].astype(str) \
                        .str.replace(',', '', regex=False) \
                        .str.replace('%', '', regex=False) \
                        .str.replace('$', '', regex=False) \
                        .str.strip() \
                        .replace(['', 'nan', 'None'], np.nan)
        df[col] = pd.to_numeric(df[col], errors='coerce')


for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')



for col in numeric_cols:
    if col in df.columns and df[col].isnull().any():
        df[col] = df.groupby('Country')[col].transform(lambda x: x.ffill().bfill())


for col in numeric_cols:
    if col in df.columns and df[col].isnull().any():
        df[col] = df.groupby('Country')[col].transform(lambda x: x.fillna(x.median()))

for col in numeric_cols:
    if col in df.columns and df[col].isnull().any():
        df[col] = df[col].fillna(df[col].median())


print(df.isnull().sum())

Country                                   0
Year                                      0
Population                                0
Reported_measles_cases                    0
Suspected_measles_cases                   0
Measles_deaths                            0
MCV1_coverage (%)                         0
MCV2_coverage (%)                         0
DTP3_coverage (%)                         0
Population_density (people/km²)           0
Urbanization (%)                          0
Birth_rate (per 1,000)                    0
Proportion_under5 (%)                     0
GDP_per_capita (US$)                      0
Health_expenditure_per_capita (US$)       0
Hospital_beds_per_1000                    0
Physicians_per_10000                      0
Vaccine_stock_status                      0
Outbreak_alert                            0
GoogleTrends_index                        0
Dropout_rate (MCV1?MCV2)                  0
Measles_incidence_rate (per million)      0
SIAs_in_past_3yrs                         0
Air_travel_volume (million passengers)    0
Internet_penetration (%)                  0
Routine_immunization_dropout (%)          0
Outbreak_Label                            0
Avg_Annual_Temperature                    0
Total_Annual_Rainfall                     0
Avg_Annual_Humidity                       0
Rainy_Season_Length                       0
Temp_Seasonality                          0
Dry_Season_Length                         0
Extreme_Rain_Days                         0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 160 non-null    object
 1   Year                                    160 non-null    int64
 2   Population                              160 non-null    int64
 3   Reported_measles_cases                  160 non-null    float64
 4   Suspected_measles_cases                 160 non-null    float64
 5   Measles_deaths                          160 non-null    float64
 6   MCV1_coverage (%)                       160 non-null    float64
 7   MCV2_coverage (%)                       160 non-null    float64
 8   DTP3_coverage (%)                       160 non-null    float64
 9   Population_density (people/km²)         160 non-null    float64
 10  Urbanization (%)                        160 non-null    float64
 11  Birth_rate (per 1,000)                  160 non-null    float64
 12  Proportion_under5 (%)                   160 non-null    float64
 13  GDP_per_capita (US$)                    160 non-null    int64
 14  Health_expenditure_per_capita (US$)     160 non-null    float64
 15  Hospital_beds_per_1000                  160 non-null    float64
 16  Physicians_per_10000                    160 non-null    float64
 17  Vaccine_stock_status                    160 non-null    object
 18  Outbreak_alert                          160 non-null    object
 19  GoogleTrends_index                      160 non-null    float64
 20  Dropout_rate (MCV1?MCV2)                160 non-null    float64
 21  Measles_incidence_rate (per million)    160 non-null    float64
 22  SIAs_in_past_3yrs                       160 non-null    object
 23  Air_travel_volume (million passengers)  160 non-null    float64
 24  Internet_penetration (%)                160 non-null    float64
 25  Routine_immunization_dropout (%)        160 non-null    float64
 26  Outbreak_Label                          160 non-null    object
 27  Avg_Annual_Temperature                  160 non-null    float64
 28  Total_Annual_Rainfall                   160 non-null    float64
 29  Avg_Annual_Humidity                     160 non-null    float64
 30  Rainy_Season_Length                     160 non-null    float64
 31  Temp_Seasonality                        160 non-null    float64
 32  Dry_Season_Length                       160 non-null    float64
 33  Extreme_Rain_Days                       160 non-null    float64
dtypes: float64(26), int64(3), object(5)
memory usage: 42.6+ KB

In [ ]:
df = df.drop('Vaccine_stock_status', axis=1)

In [ ]:
df

,Country,Year,Population,Reported_measles_cases,Suspected_measles_cases,Measles_deaths,MCV1_coverage (%),MCV2_coverage (%),DTP3_coverage (%),Population_density (people/km²),Urbanization (%),"Birth_rate (per 1,000)",Proportion_under5 (%),GDP_per_capita (US$),Health_expenditure_per_capita (US$),Hospital_beds_per_1000,Physicians_per_10000,Outbreak_alert,GoogleTrends_index,Dropout_rate (MCV1?MCV2),Measles_incidence_rate (per million),SIAs_in_past_3yrs,Air_travel_volume (million passengers),Internet_penetration (%),Routine_immunization_dropout (%),Outbreak_Label,Avg_Annual_Temperature,Total_Annual_Rainfall,Avg_Annual_Humidity,Rainy_Season_Length,Temp_Seasonality,Dry_Season_Length,Extreme_Rain_Days
0,Argentina,1990,32000000,8000.0,4300.0,150.0,75.0,90.0,80.0,15.0,87.0,22.0,9.0,4800,220.0,3.0,18.0,TRUE,50.0,2.0,250.0,No,5.0,3.0,15.0,TRUE,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
1,Argentina,2006,39200000,500.0,4300.0,10.0,95.0,90.0,95.0,16.0,89.0,18.0,8.0,7500,550.0,3.2,20.0,TRUE,50.0,2.0,12.8,Yes,14.0,45.0,4.0,TRUE,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
2,Argentina,2018,44400000,3000.0,4300.0,40.0,90.0,86.0,92.0,16.0,90.0,16.0,7.0,10000,800.0,3.5,23.0,FALSE,50.0,4.0,67.6,Yes,25.0,82.0,8.0,FALSE,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
3,Argentina,2020,45200000,400.0,4300.0,5.0,95.0,92.0,95.0,17.0,90.0,15.0,6.5,9900,850.0,3.5,24.0,TRUE,50.0,3.0,8.9,Yes,30.0,85.0,2.0,TRUE,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
4,Australia,1990,17200000,2300.0,2800.0,5.0,87.0,70.0,90.0,2.3,84.0,15.5,8.5,18000,1900.0,7.0,30.0,Yes,46.0,17.0,134.0,Yes,15.0,25.0,6.0,Outbreak,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Vietnam,2020,97300000,400.0,4300.0,5.0,97.0,90.0,96.0,300.0,38.0,15.0,12.0,3600,400.0,2.3,10.0,TRUE,50.0,7.0,4.1,Yes,7.0,70.0,3.0,TRUE,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
156,Yemen,1995,15000000,9800.0,11200.0,420.0,52.0,18.0,56.0,27.0,23.0,41.5,23.1,480,38.0,0.4,2.0,Yes,61.0,34.0,653.0,Yes,0.6,1.0,18.0,Outbreak,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
157,Yemen,2005,20500000,5500.0,6000.0,230.0,63.0,35.0,70.0,32.0,26.0,37.1,20.5,710,55.0,0.5,3.0,No,48.0,28.0,268.0,Yes,1.4,2.0,14.0,Non-outbreak,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
158,Yemen,2015,27000000,13200.0,15000.0,590.0,72.0,45.0,76.0,38.0,28.0,34.8,18.2,900,65.0,0.3,2.0,Yes,67.0,27.0,489.0,Yes,2.1,3.0,16.0,Outbreak,26.0,1190.0,73.5,7.0,2.1,5.0,34.0
159,Yemen,2022,31000000,3400.0,4100.0,190.0,75.0,52.0,79.0,40.0,31.0,31.0,16.8,1050,72.0,0.4,2.0,No,43.0,23.0,110.0,Yes,2.8,5.0,12.0,Non-outbreak,26.0,1190.0,73.5,7.0,2.1,5.0,34.0

In [ ]:
df.to_csv('cleaned_data.csv', index=False)